export const PROJECTS=[
    {   "id":0,
        "name": "P1name",
        "aline1": "211 n Ervy Street ",
        "aline2":"Dallas tx 753060",
        "stdate":"08202020",
        "pcontact":"Jim Brewin",
        "pdesig":"Director of engineering",
        "noahu":22
    },
    {   "id":1,
        "name": "P2name",
        "aline1": "211 n Ervy Street ",
        "aline2":"Dallas tx 753060",
        "stdate":"08202020",
        "pcontact":"Carl D'souza",
        "pdesig":"Director of CS",
        "noahu":18
    },
    {   "id":2,
        "name": "P3name",
        "aline1": "211 n Ervy Street ",
        "aline2":"Dallas tx 753060",
        "stdate":"08202020",
        "pcontact":"James Darvin",
        "pdesig":"Director of Corporate",
        "noahu":26
    },
    {   "id":3,
        "name": "P4name",
        "aline1": "211 n Ervy Street ",
        "aline2":"Dallas tx 753060",
        "stdate":"08202020",
        "pcontact":"Leonardo Da Vinci",
        "pdesig":"Director of institute",
        "noahu":20
    },
    {   "id":4,
        "name": "P5name",
        "aline1": "211 n Ervy Street ",
        "aline2":"Dallas tx 753060",
        "stdate":"08202020",
        "pcontact":"God",
        "pdesig":"Director of engineering",
        "noahu":30
    }
]
